repos:
  - repo: local
    hooks:
      - id: java-format
        name: Java format (Spotless)
        language: script
        entry: scripts/java-format.sh
        types: [java]
        pass_filenames: true

      - id: java-checkstyle
        name: Java lint (Checkstyle)
        language: script
        entry: scripts/java-checkstyle.sh
        types: [java]
        pass_filenames: false

      - id: ts-format
        name: Prettier
        language: script
        entry: scripts/ts-format.sh
        pass_filenames: true
        files: ^apps/.*\.(ts|tsx|css)$

      - id: files-format
        name: Format MD/YAML/JSON (Prettier)
        language: script
        entry: scripts/files-format.sh
        pass_filenames: true
        files: \.(md|markdown|yaml|yml|json)$

      - id: ts-lint
        name: ESLint
        language: script
        entry: scripts/ts-lint.sh
        pass_filenames: false
        files: ^apps/.*\.(ts|tsx)$
