repos:
  - repo: local
    hooks:
      - id: java-format
        name: Java (GJF)
        language: script
        entry: scripts/java-format.sh
        types: [java]
        pass_filenames: true

      - id: java-checkstyle
        name: Java (Checkstyle)
        language: script
        entry: scripts/java-checkstyle.sh
        types: [java]
        pass_filenames: false

      - id: ts-format
        name: Prettier
        language: script
        entry: scripts/ts-format.sh
        pass_filenames: true
        files: ^apps/.*\.(ts|tsx|json|yaml|css|md)$

      - id: ts-lint
        name: ESLint
        language: script
        entry: scripts/ts-lint.sh
        pass_filenames: false
        files: ^apps/.*\.(ts|tsx)$
